### ISSUE TITLE
Better slogan/description?

### ISSUE THREAD

**Issue by donaldpipowitch** [otbe/emock#1]
Hi there :)

I think 

> emock generates automatically mocks from you classes

should be

> emock automatically generates mocks from your classes

At least if I'm not wrong^^

But what do you think of

> smart mocks for expect

?

This is a little bit shorter and catchier and explains the _e_ in _emock_ a little bit more with the reference to expect :)

Nice lib!

**Comment by otbe** [comment]
Yeeah first issue 💃 
Changed slogan and fixed grammar 👍

**Comment by donaldpipowitch** [comment]
Fixed in 19 minutes. I hope you can keep up with this speed :D
